### ISSUE TITLE
Solution

### ISSUE THREAD

**Issue by SkrytnayaRediska** [ZenyaBelkov/Homework_lesson_11#1]
https://github.com/ZenyaBelkov/Homework_lesson_11/blob/3f19eab75b7c462ff3c28f96d97aa9b0fed23ffb/venv/oop2.py#L173

probably there is a better solution instead of using big nested levels and loop breaking

**Comment by ZenyaBelkov** [comment]
Fixed in a new brunch https://github.com/ZenyaBelkov/Homework_lesson_11/blob/1-solution/venv/oop2.py
